

/* This file contains the PRU instructions in a C array which are to  */
/* be downloaded from the host CPU to the PRU instruction memory.     */
/* This file is generated by the PRU assembler.                       */

const unsigned int Arr_pru[] =  {
     0x240000e0,
     0xf5006081,
     0x240000e0,
     0xf1042082,
     0x0104e3e3,
     0xcf00e2fd,
     0x0102e3e3,
     0x04e4e3e5,
     0x1d00e2e2,
     0x0101e1e1,
     0xe5006081,
     0x10e3e3e4,
     0x2400231f,
     0x0107e3e3,
     0x21000200,
     0x2400231f,
     0x2a000000 };

